### ISSUE TITLE
Not showing transmission & weird weather issue

### ISSUE THREAD

**Issue by manderso7** [darkcloud784/Home-Dashboard#1]
Enjoying the dash for the most part, but having some troubles.  
1. Weather shows weird stuff, like -56, partly cloudy, feels like -77  
2. Unable to see any transmission data.  
I've set my latitude, longitude & weather_key in config.php, and set Show_Torrents to 'true', and included my torrent_username and torrent_password, but nothing shows in the torrent section. Do you have any thoughts that could help here?

**Comment by darkcloud784** [comment]
@manderso7 
The Weather is directly parsed from forecast.io, so thats what it say there. You can check your webserver for errors indicating if there was a problem parsing it but if not, then unfortunately thats just what they (forecast.io) is reporting for your area.
For torrents, make sure there are no errors within your webserver or displayed. If there are, please give me what the errors are saying. Additionally ensure you have all the information correctly added in. IE make sure there is JUST THE IP listed in Torrent_Server_IP with no spaces or such.
